### ISSUE TITLE
Repos not recognized correctly ?

### ISSUE THREAD

**Issue by jkoivuko** [plexsystems/sinker#28]
Hey, love the tool!
However, looks like a lot of repo's are not recognized by `sinker create` cmd. I had to manually add `host:` to the manifest yaml for following public repo's we use, but wish to sync to our own private repo:

registry.opensource.zalan.do
docker.elastic.co

Example of the `image:` definition in k8s: `docker.elastic.co/elasticsearch/elasticsearch:7.4.0`
This was not properly added to image manifest and sinker was trying to pull it from default (docker hub).

What's up with that. Am I doing something wrong?

**Comment by jpreese** [comment]
Thanks for opening the issue @jkoivuko -- this should be resolved in `v0.11.1`. Could you please let me know if that successfully picks up the hosts that you've outlined here?

**Comment by jkoivuko** [comment]
Thanks. Can confirm that it works as expected now. Thanks for the quick fix!
