### ISSUE TITLE
Cannot find image on Harbor Registry

### ISSUE THREAD

**Issue by hoihrig** [plexsystems/sinker#35]
When connecting to a Registry running [Harbor ](https://goharbor.io), sinker is unable to check if an image exists as Harbor is returning a 404 NOT_FOUND instead of MANIFEST_UNKNOWN

Observed behaviour:
`time="2020-09-17T21:07:13+02:00" level=info msg="Finding images that need to be pushed ..."
Error: push: image exists at remote: get image: GET https://harbor.myreg.org/v2/xyz/coreos/prometheus-operator/manifests/v0.38.0: NOT_FOUND: artifact xyz/coreos/prometheus-operator:v0.38.0 not found`

Expected behaviour:
Image gets pushed

**Comment by jpreese** [comment]
Resolved via #36. Available in [v0.13.1](https://github.com/plexsystems/sinker/releases/tag/v0.13.1).

Thanks @hoihrig !
