### ISSUE TITLE
Update docker image for new releases

### ISSUE THREAD

**Issue by nickperkins** [plexsystems/sinker#54]
Docker image for v0.14 was pushed to docker hub not not the latest release.

https://hub.docker.com/r/plexsystems/sinker

**Comment by jpreese** [comment]
Sorry about that! [v0.15.0](https://hub.docker.com/layers/plexsystems/sinker/v0.15.0/images/sha256-de2c2203ada1ca67839558651fc5473aca622f422b83ab6b69c4eea504d4f836?context=explore) has been pushed.
