### ISSUE TITLE
Target repository needs to be created first

### ISSUE THREAD

**Issue by iJebus** [plexsystems/sinker#55]
Maybe I'm missing something obvious, but I had expected sinker to create repositories on the target for me.

```yaml
target:
  host: <account-number>.dkr.ecr.ap-southeast-2.amazonaws.com
sources:
- repository: coreos/prometheus-operator
  host: quay.io
  tag: v0.40.0
```

```sh
$ sinker --version
sinker version v0.15.0
$ sinker push
INFO[0000] Finding images that need to be pushed ...    
Error: push: image exists at remote: get image: GET https://<account-number>.dkr.ecr.ap-southeast-2.amazonaws.com/v2/coreos/prometheus-operator/manifests/v0.40.0: NAME_UNKNOWN: The repository with name 'coreos/prometheus-operator' does not exist in the registry with id '<account-number>'
```

If I create the repository manually in ECR and then try again.

```sh
$ sinker push     
INFO[0000] Finding images that need to be pushed ...    
INFO[0000] Pulling quay.io/coreos/prometheus-operator:v0.40.0 
INFO[0010] Pulling quay.io/coreos/prometheus-operator:v0.40.0 (Processing 937640B of 11251687B) 
INFO[0013] Pushing <account-number>.dkr.ecr.ap-southeast-2.amazonaws.com/coreos/prometheus-operator:v0.40.0 
INFO[0016] Pushing <account-number>.dkr.ecr.ap-southeast-2.amazonaws.com/coreos/prometheus-operator:v0.40.0 (Processing 8291328B of 35590144B) 
INFO[0024] All images have been pushed!
```

Is this expected, or am I using it incorrectly, or? 🤔

**Comment by jpreese** [comment]
Thanks for the error report, @iJebus! I think https://github.com/plexsystems/sinker/pull/56 should solve this.

I'll do some further testing and cut a release shortly.

**Comment by iJebus** [comment]
I wasn't sure so had to check, but the repo needs to be created first. Docker tried a few times with a back-off delay but eventually gave up.

```sh
$ docker push <account-number>.dkr.ecr.ap-southeast-2.amazonaws.com/alpine1:latest
The push refers to repository [<account-number>.dkr.ecr.ap-southeast-2.amazonaws.com/alpine1]
8d3ac3489996: Retrying in 1 seconds
EOF
```

**Comment by jpreese** [comment]
Ok, I see. That appears to be a limitation of ECR then. I just tried with DockerHub, and they _will_ create the repository for you if it does not exist. So even with the proposed change, we'd end up with the same issue.

I'd need to dig into it some to see how best to create the repository ahead of time before the push when pushing to ECR.

**Comment by iJebus** [comment]
No rush, honestly, I'm just glad I hadn't missed something in the documentation about how to use it properly 😅.

**Comment by jpreese** [comment]
Nope! Nothing missed 😄
