### ISSUE TITLE
Feature Request - Add a dry-run functionnality

### ISSUE THREAD

**Issue by aslafy-z** [plexsystems/sinker#58]
With the `--dry-run` flag enabled, Sinker looks for images that needs sync and print them without doing the actual pull-push action.

**Comment by jpreese** [comment]
@aslafy-z a [--dry-run](https://github.com/plexsystems/sinker#--dryrun-flag-optional) flag currently exists within Sinker. Is there anything about its implementation that you're wanting to change and/or enhance?

**Comment by aslafy-z** [comment]
Oh well, I missed it. It looks like it fulfils my needs. Thank you @jpreese.
