### ISSUE TITLE
GHCR does not support nested path

### ISSUE THREAD

**Issue by mnasiadka** [plexsystems/sinker#60]
Github Container Registry also does not support nested path.

**Comment by jpreese** [comment]
https://github.com/plexsystems/sinker/pull/34 actually added GHCR as a registry that supports this. Is this actually not the case?

**Comment by mnasiadka** [comment]
#34 was for GCR - Google Container Registry, GHCR is GitHub Container Registry - and nested paths do not work in GHCR :-)

**Comment by jpreese** [comment]
.. my bad. Letters are hard.
